# Generated by Django 5.0.4 on 2024-04-09 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_city_company_description_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
    ]
